version: '3'
services:
  db:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - ./.env
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"
        ]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always
    ports:
      - "5432:5432"

  app:
    build: .
    image: 513600691417.dkr.ecr.eu-west-1.amazonaws.com/dashi-repository:latest
    restart: always
    ports:
      - "5001:5000"
    env_file:
      - ./.env
    command: /app/bin/dashi-start.sh
    depends_on:
      db:
        condition: service_healthy

  sidecar:
    build: .
    image: 513600691417.dkr.ecr.eu-west-1.amazonaws.com/dashi-repository:latest
    restart: always
    env_file:
      - ./.env
    command: /app/bin/ci-poller-start.sh
    depends_on:
      db:
        condition: service_healthy
      app:
        condition: service_started

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  pgdata:
