version: '3'
services:
  db:
    build:
      context: .
      dockerfile: ./dockers/db/Dockerfile
    image: ${REPOSITORY_URI}:${IMAGE_TAG}_db
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: ./dockers/app/Dockerfile
    image: ${REPOSITORY_URI}:${IMAGE_TAG}
    ports:
      - "5000:5000"
    environment:
      - "DATABASE_URL=${DATABASE_URL}"
    command: "flask run --host=0.0.0.0"
    depends_on:
      - db

  nginx:
    build:
      context: .
      dockerfile: ./dockers/nginx/Dockerfile
    image: ${REPOSITORY_URI}:${IMAGE_TAG}_nginx
    volumes:
      - /home/ubuntu/dashi/dashi.crt:/nginx/dashi.crt
      - /home/ubuntu/dashi/dashi.key:/nginx/dashi.key
    ports:
      - "80:80"
    depends_on:
      - app

  gather:
    build:
      context: .
      dockerfile: ./dockers/app/Dockerfile
    image: ${REPOSITORY_URI}:${IMAGE_TAG}
    environment:
      - "DATABASE_URL=${DATABASE_URL}"
      - "CIRCLE_CI_TOKEN=${CIRCLE_CI_TOKEN}"
      - "GITHUB_TOKEN=${GITHUB_TOKEN}"
      - "SLEEP_SECONDS=60"
    command: "/app/dockers/app/gather-start.sh"
    depends_on:
      - db
      - app

  pqadmin:
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    environment:
      - "PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}"
      - "PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}"
      - "PGADMIN_DISABLE_POSTFIX=${PGADMIN_DISABLE_POSTFIX}"
      - "PGADMIN_LISTEN_ADDRESS=${PGADMIN_LISTEN_ADDRESS}"
      - "PGADMIN_LISTEN_PORT=${PGADMIN_LISTEN_PORT}"
