"""empty message

Revision ID: 1b1518911ff7
Revises: fd465a61f704
Create Date: 2022-07-27 01:38:30.574039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b1518911ff7'
down_revision = 'fd465a61f704'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_workflow_workflowId', table_name='workflow')
    op.drop_table('workflow')
    op.add_column('pipeline', sa.Column('workflowId', sa.String(), nullable=True))
    op.add_column('pipeline', sa.Column('status', sa.String(), nullable=True))
    op.add_column('pipeline', sa.Column('workflowName', sa.String(), nullable=True))
    op.create_index(op.f('ix_pipeline_workflowId'), 'pipeline', ['workflowId'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pipeline_workflowId'), table_name='pipeline')
    op.drop_column('pipeline', 'workflowName')
    op.drop_column('pipeline', 'status')
    op.drop_column('pipeline', 'workflowId')
    op.create_table('workflow',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('workflowId', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pipelineId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['pipelineId'], ['pipeline.pipelineId'], name='workflow_pipelineId_fkey'),
    sa.PrimaryKeyConstraint('id', name='workflow_pkey')
    )
    op.create_index('ix_workflow_workflowId', 'workflow', ['workflowId'], unique=False)
    # ### end Alembic commands ###
