"""empty message

Revision ID: 28e61136e73f
Revises: 33336ff994e8
Create Date: 2022-08-03 15:40:19.224975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28e61136e73f'
down_revision = '33336ff994e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline', sa.Column('commitId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pipeline', 'commits', ['commitId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pipeline', type_='foreignkey')
    op.drop_column('pipeline', 'commitId')
    # ### end Alembic commands ###
