"""empty message

Revision ID: 3c66c9a64723
Revises: 9ed5a6d0ea1b
Create Date: 2022-07-25 17:57:59.906720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c66c9a64723'
down_revision = '9ed5a6d0ea1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_commits_message', table_name='commits')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_commits_message', 'commits', ['message'], unique=False)
    # ### end Alembic commands ###
