"""empty message

Revision ID: 3e6d455a49d9
Revises: 395d2db378c5
Create Date: 2022-07-18 17:30:07.726902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e6d455a49d9'
down_revision = '395d2db378c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow', sa.Column('pipelineId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'workflow', 'pipeline', ['pipelineId'], ['pipelineId'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflow', type_='foreignkey')
    op.drop_column('workflow', 'pipelineId')
    # ### end Alembic commands ###
