"""empty message

Revision ID: 47e84e16b150
Revises: 1b1518911ff7
Create Date: 2022-07-29 14:15:55.661191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47e84e16b150'
down_revision = '1b1518911ff7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflowId', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_name'), 'job', ['name'], unique=False)
    op.create_index(op.f('ix_job_workflowId'), 'job', ['workflowId'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_workflowId'), table_name='job')
    op.drop_index(op.f('ix_job_name'), table_name='job')
    op.drop_table('job')
    # ### end Alembic commands ###
