"""empty message

Revision ID: 5363d8cf1bae
Revises: 
Create Date: 2022-07-20 14:05:21.895389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5363d8cf1bae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projectSlug', sa.String(), nullable=True),
    sa.Column('pipelineId', sa.Integer(), nullable=True),
    sa.Column('branch', sa.String(), nullable=True),
    sa.Column('revision', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_branch'), 'pipeline', ['branch'], unique=False)
    op.create_index(op.f('ix_pipeline_pipelineId'), 'pipeline', ['pipelineId'], unique=True)
    op.create_index(op.f('ix_pipeline_projectSlug'), 'pipeline', ['projectSlug'], unique=False)
    op.create_table('workflow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflowId', sa.String(), nullable=True),
    sa.Column('pipelineId', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['pipelineId'], ['pipeline.pipelineId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_workflowId'), 'workflow', ['workflowId'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_workflowId'), table_name='workflow')
    op.drop_table('workflow')
    op.drop_index(op.f('ix_pipeline_projectSlug'), table_name='pipeline')
    op.drop_index(op.f('ix_pipeline_pipelineId'), table_name='pipeline')
    op.drop_index(op.f('ix_pipeline_branch'), table_name='pipeline')
    op.drop_table('pipeline')
    # ### end Alembic commands ###
