"""empty message

Revision ID: 54aac1f43e71
Revises: a3a528f6d4e2
Create Date: 2023-06-06 01:38:11.470131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54aac1f43e71'
down_revision = 'a3a528f6d4e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repositories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repositories_name'), 'repositories', ['name'], unique=True)
    op.create_index(op.f('ix_repositories_title'), 'repositories', ['title'], unique=True)
    op.create_table('branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('repository_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pipelines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('repository_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('benchmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commit_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('test_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['commit_id'], ['commits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_benchmarks_status'), 'benchmarks', ['status'], unique=False)
    op.create_index(op.f('ix_benchmarks_test_name'), 'benchmarks', ['test_name'], unique=False)
    op.create_table('pipeline_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_id', sa.Integer(), nullable=True),
    sa.Column('commit_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('html_url', sa.String(), nullable=True),
    sa.Column('workflow_id', sa.String(), nullable=True),
    sa.Column('run_number', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['commit_id'], ['commits.id'], ),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_id', 'run_number', name='_workflow_run_uc')
    )
    op.create_index(op.f('ix_pipeline_statuses_run_number'), 'pipeline_statuses', ['run_number'], unique=False)
    op.create_index(op.f('ix_pipeline_statuses_workflow_id'), 'pipeline_statuses', ['workflow_id'], unique=False)
    op.drop_index('ix_benchmark_commit', table_name='benchmark')
    op.drop_index('ix_benchmark_status', table_name='benchmark')
    op.drop_index('ix_benchmark_testName', table_name='benchmark')
    op.drop_table('benchmark')
    op.drop_index('ix_pipeline_branch', table_name='pipeline')
    op.drop_index('ix_pipeline_pipelineId', table_name='pipeline')
    op.drop_index('ix_pipeline_projectSlug', table_name='pipeline')
    op.drop_index('ix_pipeline_workflowId', table_name='pipeline')
    op.drop_table('pipeline')
    op.add_column('commits', sa.Column('branch_id', sa.Integer(), nullable=True))
    op.add_column('commits', sa.Column('hash', sa.String(), nullable=True))
    op.add_column('commits', sa.Column('author', sa.String(), nullable=True))
    op.drop_index('ix_commits_branch', table_name='commits')
    op.drop_index('ix_commits_commit', table_name='commits')
    op.drop_index('ix_commits_date', table_name='commits')
    op.drop_index('ix_commits_projectSlug', table_name='commits')
    op.create_foreign_key(None, 'commits', 'branches', ['branch_id'], ['id'])
    op.drop_column('commits', 'projectSlug')
    op.drop_column('commits', 'branch')
    op.drop_column('commits', 'commit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commits', sa.Column('commit', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('commits', sa.Column('branch', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('commits', sa.Column('projectSlug', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'commits', type_='foreignkey')
    op.create_index('ix_commits_projectSlug', 'commits', ['projectSlug'], unique=False)
    op.create_index('ix_commits_date', 'commits', ['date'], unique=False)
    op.create_index('ix_commits_commit', 'commits', ['commit'], unique=False)
    op.create_index('ix_commits_branch', 'commits', ['branch'], unique=False)
    op.drop_column('commits', 'author')
    op.drop_column('commits', 'hash')
    op.drop_column('commits', 'branch_id')
    op.create_table('pipeline',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('projectSlug', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pipelineId', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('branch', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('revision', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('workflowId', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('workflowName', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('commitId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['commitId'], ['commits.id'], name='pipeline_commitId_fkey'),
    sa.PrimaryKeyConstraint('id', name='pipeline_pkey')
    )
    op.create_index('ix_pipeline_workflowId', 'pipeline', ['workflowId'], unique=False)
    op.create_index('ix_pipeline_projectSlug', 'pipeline', ['projectSlug'], unique=False)
    op.create_index('ix_pipeline_pipelineId', 'pipeline', ['pipelineId'], unique=False)
    op.create_index('ix_pipeline_branch', 'pipeline', ['branch'], unique=False)
    op.create_table('benchmark',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('testName', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('commit', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='benchmark_pkey')
    )
    op.create_index('ix_benchmark_testName', 'benchmark', ['testName'], unique=False)
    op.create_index('ix_benchmark_status', 'benchmark', ['status'], unique=False)
    op.create_index('ix_benchmark_commit', 'benchmark', ['commit'], unique=False)
    op.drop_index(op.f('ix_pipeline_statuses_workflow_id'), table_name='pipeline_statuses')
    op.drop_index(op.f('ix_pipeline_statuses_run_number'), table_name='pipeline_statuses')
    op.drop_table('pipeline_statuses')
    op.drop_index(op.f('ix_benchmarks_test_name'), table_name='benchmarks')
    op.drop_index(op.f('ix_benchmarks_status'), table_name='benchmarks')
    op.drop_table('benchmarks')
    op.drop_table('pipelines')
    op.drop_table('branches')
    op.drop_index(op.f('ix_repositories_title'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_name'), table_name='repositories')
    op.drop_table('repositories')
    # ### end Alembic commands ###
