"""empty message

Revision ID: 6b8211320ded
Revises: baa9adcbd1d5
Create Date: 2022-10-13 14:04:56.332525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b8211320ded'
down_revision = 'baa9adcbd1d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('benchmark', sa.Column('testName', sa.String(), nullable=True))
    op.create_index(op.f('ix_benchmark_testName'), 'benchmark', ['testName'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_benchmark_testName'), table_name='benchmark')
    op.drop_column('benchmark', 'testName')
    # ### end Alembic commands ###
