"""empty message

Revision ID: 6e6e549117df
Revises: c86ed5a1a31b
Create Date: 2023-08-15 04:09:21.831188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e6e549117df'
down_revision = 'c86ed5a1a31b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_commits_hash'), 'commits', ['hash'], unique=False)
    op.create_index(op.f('ix_commits_tag'), 'commits', ['tag'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_commits_tag'), table_name='commits')
    op.drop_index(op.f('ix_commits_hash'), table_name='commits')
    # ### end Alembic commands ###
