"""empty message

Revision ID: 9ed5a6d0ea1b
Revises: f575388e707b
Create Date: 2022-07-25 14:36:20.680590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ed5a6d0ea1b'
down_revision = 'f575388e707b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commits', sa.Column('branch', sa.String(), nullable=True))
    op.create_index(op.f('ix_commits_branch'), 'commits', ['branch'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_commits_branch'), table_name='commits')
    op.drop_column('commits', 'branch')
    # ### end Alembic commands ###
