"""empty message

Revision ID: a17691311fc9
Revises: 3e6d455a49d9
Create Date: 2022-07-19 03:54:10.025834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a17691311fc9'
down_revision = '3e6d455a49d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline', sa.Column('projectSlug', sa.String(), nullable=True))
    op.add_column('pipeline', sa.Column('number', sa.Integer(), nullable=True))
    op.add_column('pipeline', sa.Column('branch', sa.String(), nullable=True))
    op.add_column('pipeline', sa.Column('revision', sa.String(), nullable=True))
    op.drop_column('pipeline', 'name')
    op.add_column('workflow', sa.Column('status', sa.String(), nullable=True))
    op.add_column('workflow', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow', 'name')
    op.drop_column('workflow', 'status')
    op.add_column('pipeline', sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.drop_column('pipeline', 'revision')
    op.drop_column('pipeline', 'branch')
    op.drop_column('pipeline', 'number')
    op.drop_column('pipeline', 'projectSlug')
    # ### end Alembic commands ###
