"""empty message

Revision ID: b9360710b6bb
Revises: 358feed13814
Create Date: 2022-11-21 13:20:07.588638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9360710b6bb'
down_revision = '358feed13814'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_benchmark_branch', table_name='benchmark')
    op.drop_index('ix_benchmark_workflowId', table_name='benchmark')
    op.drop_column('benchmark', 'branch')
    op.drop_column('benchmark', 'workflowId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('benchmark', sa.Column('workflowId', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('benchmark', sa.Column('branch', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_benchmark_workflowId', 'benchmark', ['workflowId'], unique=False)
    op.create_index('ix_benchmark_branch', 'benchmark', ['branch'], unique=False)
    # ### end Alembic commands ###
