"""empty message

Revision ID: c86ed5a1a31b
Revises: fe108f427881
Create Date: 2023-08-06 15:45:52.997740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c86ed5a1a31b'
down_revision = 'fe108f427881'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commits', sa.Column('tag', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commits', 'tag')
    # ### end Alembic commands ###
