"""empty message

Revision ID: d167f3bb5251
Revises: 5363d8cf1bae
Create Date: 2022-07-20 15:28:05.131472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd167f3bb5251'
down_revision = '5363d8cf1bae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline', sa.Column('message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipeline', 'message')
    # ### end Alembic commands ###
