"""empty message

Revision ID: d3261b9d7668
Revises: 1566d1139605
Create Date: 2022-07-20 00:50:44.145183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3261b9d7668'
down_revision = '1566d1139605'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'workflow', ['workflowId'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflow', type_='unique')
    # ### end Alembic commands ###
