"""empty message

Revision ID: d592a633bee4
Revises: 28e61136e73f
Create Date: 2022-08-10 17:52:39.269364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd592a633bee4'
down_revision = '28e61136e73f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_job_name', table_name='job')
    op.drop_index('ix_job_workflowId', table_name='job')
    op.drop_table('job')
    op.add_column('commits', sa.Column('date', sa.TIMESTAMP(), nullable=True))
    op.create_index(op.f('ix_commits_date'), 'commits', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_commits_date'), table_name='commits')
    op.drop_column('commits', 'date')
    op.create_table('job',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('workflowId', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='job_pkey')
    )
    op.create_index('ix_job_workflowId', 'job', ['workflowId'], unique=False)
    op.create_index('ix_job_name', 'job', ['name'], unique=False)
    # ### end Alembic commands ###
